engines:
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 50
  fixme:
    enabled: true
  radon:
    enabled: true
  paths:
  - "**.py"
exclude_paths: []
