---
engines:
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
  paths:
  - "**.py"
exclude_paths: []
