---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
            args: [--maxkb=800]
          - id: check-ast
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-yaml
          - id: detect-private-key
          - id: destroyed-symlinks
          - id: fix-byte-order-marker
          - id: forbid-new-submodules
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: trailing-whitespace
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.9.0
      hooks:
          - id: reorder-python-imports
            types: [python]
            args: [--py39-plus, --exit-zero-even-if-changed]
    - repo: https://github.com/psf/black
      rev: 23.3.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.1.1
      hooks:
          - id: mypy
            # language: system
            additional_dependencies: [numpy, types-PyYAML, types-psutil]
            types: [python]
            require_serial: true
            # verbose: true
    - repo: https://github.com/pycqa/flake8
      rev: 6.0.0
      hooks:
          - id: flake8
            types: [python]
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: pylint
            language: python
            # language: system
            types: [python]
            require_serial: true
            args: [-rn, -sn]
