language: python
python: 3.6

cache: pip

install:
  - "pip install coveralls codeclimate-test-reporter"
  - "pip install -r requirements.txt"

# command to run tests
script:
#  - flake8 .
#  - pytest --cov=artistools
  - coverage run --source artistools setup.py test

after_success:
#  - codecov
  - coveralls
  - codeclimate-test-reporter