language: python
python: 3.6

cache: pip

install:
  - "pip install coveralls codeclimate-test-reporter"
  - "pip install -r requirements.txt"

before_script: # configure a headless display to test plot generation
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
#  - flake8 .
#  - pytest --cov=artistools
  - coverage run --source artistools setup.py test

after_success:
#  - codecov
  - coveralls
  - codeclimate-test-reporter

git:
  lfs_skip_smudge: false