coverage:
  status:
    project:
      default:
        threshold: 1%
    #     target: auto
    #     if_ci_failed: failure #success, failure, error, ignore
    #     informational: false
    #     only_pulls: true
    patch:
      default:
        target: auto
        threshold: 0%
        if_ci_failed: ignore #success, failure, error, ignore
        informational: true
        only_pulls: false
