coverage:
  status:
    # project:
    #   default:
    #     target: auto
    #     threshold: 0%
    #     base: auto
    #     if_ci_failed: ignore #success, failure, error, ignore
    #     informational: true
    #     only_pulls: true
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_ci_failed: ignore #success, failure, error, ignore
        only_pulls: true
