[build-system]
requires = ["psutil>=5.9.0", "setuptools>=45", "setuptools_scm[toml]>=6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "artistools"
authors = [
    {name = "ARTIS Collaboration", email = "luke.shingles@gmail.com"},
]
description="Plotting and analysis tools for the ARTIS 3D supernova radiative transfer code."
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: Matplotlib",
    "Intended Audience :: Science/Research",
]
dynamic = ["version", "dependencies", "entry-points", "readme"]
requires-python = ">=3.9"

#[project.scripts]
#atcompletions = "artistoolscompletions.sh"

#[tool.setuptools]
#packages = ["artistools"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
dependencies = {file = ["requirements.txt"]}
#entry-points = {attr = "artistools.commands.console_scripts"}

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 120
preview = true

[tool.mypy]
python_version = '3.11'
exclude = "(build)|(tests)"
packages = "artistools"
ignore_missing_imports = true
warn_unused_configs = true
#files = 'artistools/**/*.py'
plugins = 'numpy.typing.mypy_plugin'

[[tool.mypy.overrides]]
module = [
    "artistools.estimators.estimators",
    "artistools.inputmodel",
    "artistools.lightcurve",
    "artistools.misc",
#    "artistools.packets",
    "artistools.spectra.spectra",
]
check_untyped_defs = true
disallow_untyped_defs = true
warn_return_any = false

[tool.pylint]
max-line-length = 120
errors-only = true

[tool.pylint.typecheck]
ignored-modules = ["astropy", "extinction"]

[tool.setuptools_scm]
write_to = "_version.py"
local_scheme = "no-local-version"
