[build-system]
requires = ["psutil>=5.9.0", "setuptools>=45", "setuptools_scm[toml]>=6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "artistools"
authors = [
    {name = "ARTIS Collaboration", email = "luke.shingles@gmail.com"},
]
description="Plotting and analysis tools for the ARTIS 3D supernova radiative transfer code."
#readme = "README.md"
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version", "dependencies", "entry-points", "readme"]
requires-python = ">=3.8"

#[project.scripts]
#atcompletions = "artistoolscompletions.sh"

[tool.setuptools]
packages = ["artistools"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
dependencies = {file = ["requirements.txt"]}
#entry-points = {attr = "artistools.commands.console_scripts"}


[tool.black]
line-length = 120
preview = true

[tool.mypy]
python_version = '3.10'
exclude = "(build)|(tests)"
ignore_missing_imports = true
files = 'artistools/**/*.py'
plugins = 'numpy.typing.mypy_plugin'

[tool.pylint]
max-line-length = 120
errors-only = true

[tool.pylint.typecheck]
ignored-modules = ["astropy", "extinction"]

[tool.setuptools_scm]
write_to = "_version.py"
local_scheme = "no-local-version"
