[build-system]
requires = ["psutil>=5.9.0", "setuptools>=45", "setuptools_scm[toml]>=6.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "artistools"
authors = [
    {name = "ARTIS Collaboration", email = "luke.shingles@gmail.com"},
]
description="Plotting and analysis tools for the ARTIS 3D supernova radiative transfer code."
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Framework :: Matplotlib",
    "Intended Audience :: Science/Research",
]
dynamic = ["version", "dependencies", "entry-points", "readme"]
requires-python = ">=3.9"

#[project.scripts]
#atcompletions = "artistoolscompletions.sh"

#[tool.setuptools]
#packages = ["artistools"]

[tool.setuptools.dynamic]
readme = {file = ["README.md"]}
dependencies = {file = ["requirements.txt"]}
#entry-points = {attr = "artistools.commands.console_scripts"}

[tool.setuptools.packages.find]
where = ["."]

[tool.black]
line-length = 120
preview = true

[tool.mypy]
python_version = '3.11'
exclude = "(build)|(tests)"
packages = "artistools"
ignore_missing_imports = true
warn_unused_configs = true
#files = 'artistools/**/*.py'
plugins = 'numpy.typing.mypy_plugin'
scripts_are_modules = true
strict_equality = true
pretty = true
error_summary = true
enable_error_code = [
  "redundant-expr",
  "truthy-bool",
  "ignore-without-code",
]

[[tool.mypy.overrides]]
module = [
    "artistools.estimators.estimators",
    "artistools.inputmodel",
    "artistools.lightcurve",
    "artistools.misc",
#    "artistools.packets",
    "artistools.spectra.spectra",
]
check_untyped_defs = true
disallow_untyped_defs = true
warn_return_any = false
#strict = true

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 120
disable = """
    broad-exception-caught,
    cell-var-from-loop,
    cyclic-import,
    dangerous-default-value,
    eval-used,
    fixme,
    global-statement,
    global-variable-not-assigned,
    missing-function-docstring,
    missing-module-docstring,
    import-outside-toplevel,
    invalid-name,
    line-too-long,
    protected-access,
    redefined-builtin,
    redefined-outer-name,
    reimported,
    too-many-arguments,
    too-many-branches,
    too-many-lines,
    too-many-locals,
    too-many-statements,
    undefined-loop-variable,
    unused-argument,
    unused-variable,
    unspecified-encoding,
    C,
    R,
"""
enable = """
    unused-import,
"""
[tool.pylint.typecheck]
ignored-modules = ["astropy", "extinction"]

[tool.setuptools_scm]
write_to = "_version.py"
local_scheme = "no-local-version"
