---
name: Benchmark with CodSpeed
permissions:
    contents: read
on:
    push:
        branches:
            - main
    workflow_dispatch:
    repository_dispatch:
        types: [trigger_checks]
jobs:
    codspeed-benchmarks:
        timeout-minutes: 180
        runs-on: ubuntu-26.04-arm
        env:
            PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
            UV_FROZEN: 1
        name: codspeed benchmarks
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup uv
              uses: astral-sh/setup-uv@v8.2.0
              id: setup-uv
              with:
                  activate-environment: true
                  cache-suffix: codspeed
                  cache-dependency-glob: '**/uv.lock'

            - name: Cache cargo and rust build
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      rust/target/
                  key: codspeed-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock')
                      }}-${{ github.run_id }}
                  restore-keys: |
                      codspeed-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock') }}-
                      codspeed-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-
                      codspeed-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-
                      cargo-rust-target-${{ runner.os }}${{ runner.arch }}-

            - name: Install artistools
              run: |
                  sudo apt-get install -y liblzma-dev
                  rustup update stable
                  uv sync --compile-bytecode

            - name: Download/extract test data
              working-directory: tests/data/
              run: source ./setuptestdata.sh

            - name: Run benchmarks
              uses: CodSpeedHQ/action@v4
              with:
                  mode: simulation
                  token: ${{ secrets.CODSPEED_TOKEN }}
                  run: pytest --codspeed
