---
name: Build wheels and deploy to TestPyPI

on:
    push:
        branches:
            - '*'
        tags:
            - '*'
    repository_dispatch:
        types: [trigger_checks]

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                # macos-13 is an intel runner, macos-14 is apple silicon
                os: [ubuntu-latest, macos-13, macos-14]
            fail-fast: false
        env:
            CIBW_ENVIRONMENT_PASS_LINUX: SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ARTISTOOLS

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade setuptools setuptools_scm[toml] uv
                  echo "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ARTISTOOLS=$(python3 -m setuptools_scm --strip-dev)" >> $GITHUB_ENV

            - name: Build wheels
              uses: pypa/cibuildwheel@v2.19.1

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                  path: ./wheelhouse/*.whl

    build_sdist:
        name: Build source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade setuptools setuptools_scm[toml] setuptools-rust wheel twine build
                  echo "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ARTISTOOLS=$(python3 -m setuptools_scm --strip-dev)" >> $GITHUB_ENV

            - name: Build sdist
              run: |
                  export SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ARTISTOOLS=$(python3 -m setuptools_scm --strip-dev)
                  python3 -m build --sdist

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-sdist
                  path: dist/*.tar.gz

    upload_test_pypi:
        needs: [build_wheels, build_sdist]
        runs-on: ubuntu-latest
        environment: test
        permissions:
            id-token: write
        # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version-file: .python-version

            - uses: actions/download-artifact@v4
              with:
                  # unpacks all CIBW artifacts into dist/
                  pattern: cibw-*
                  path: dist
                  merge-multiple: true

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade setuptools setuptools_scm[toml] setuptools-rust wheel twine build
                  echo "SETUPTOOLS_SCM_PRETEND_VERSION_FOR_ARTISTOOLS=$(python3 -m setuptools_scm --strip-dev)" >> $GITHUB_ENV

            - name: Publish package to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  skip-existing: true
                  verbose: false
                  repository-url: https://test.pypi.org/legacy/
