name: Lint

on:
  push:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"

  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # with:
        #   # this is needed to the get the automatic version correct
        #   fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip wheel flake8
          python3 -m pip install -r requirements.txt

          # upgrade all installed packages to their latest versions
          # python3 -m pip list --format=freeze --outdated | cut -d '=' -f1 | xargs -n1 python3 -m pip install --upgrade

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        # with:
        #   # this is needed to the get the automatic version correct
        #   fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          cache: "pip"
          python-version-file: ".python-version"

      # - name: Install dependencies
      #   run: |
      #     python3 -m pip install --upgrade pip wheel
      #     python3 -m pip install -r requirements.txt

      - name: Lint with mypy
        run: |
          mypy --install-types
          mypy --ignore-missing-imports --python-executable python3 artistools/
