---
name: Test and lint
permissions:
    contents: read
on:
    push:
    merge_group:
    schedule:
        - cron: 0 10 * * 2
    workflow_dispatch:
    repository_dispatch:
        types: [trigger_checks]
env:
    PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
    RUFF_OUTPUT_FORMAT: github
    UV_FROZEN: 1
jobs:
    lint:
        name: Format, lint, and type check
        runs-on: ubuntu-26.04-arm
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - uses: astral-sh/setup-uv@v8.2.0
              id: setup-uv
              with:
                  activate-environment: true
                  cache-suffix: lint
                  prune-cache: false
                  cache-dependency-glob: '**/uv.lock'

            - name: Cache cargo and rust build
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      rust/target/
                  key: lint-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock')
                      }}-${{ github.run_id }}
                  restore-keys: |
                      lint-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock') }}-
                      lint-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-
                      lint-cargo-rust-target-${{ runner.os }}${{ runner.arch }}-
                      cargo-rust-target-${{ runner.os }}${{ runner.arch }}-

            - name: Install artistools[extras]
              run: |
                  uv sync --all-extras

            - name: Run Ruff
              if: always()
              run: |
                  uv run -- ruff --version
                  uv run -- ruff check --exit-non-zero-on-fix --no-fix

            - name: Run Ruff Format
              if: always()
              run: uv run -- ruff format --check --exit-non-zero-on-format

            - name: Run basedpyright
              if: always()
              run: uv run -- basedpyright --warnings

            - name: Run pyrefly
              if: always()
              run: uv run -- pyrefly check --output-format github

            - name: Run mypy
              if: always()
              run: uv run -- mypy

            - name: Run prek pre-commit checks
              uses: j178/prek-action@v2

            - name: Run rust clippy
              if: always()
              working-directory: rust/
              run: |
                  rustup component add clippy
                  cargo clippy --all-features -- -D warnings -D clippy::pedantic

    pytest:
        timeout-minutes: 120
        strategy:
            fail-fast: false
            matrix:
                python-version: ['3.12', '3.13', '3.14', 3.14t]
        runs-on: ubuntu-26.04${{ !endsWith(matrix.python-version, 't') && '-arm' || '' }}
        name: pytest python ${{ matrix.python-version }}
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Setup uv
              uses: astral-sh/setup-uv@v8.2.0
              id: setup-uv
              with:
                  activate-environment: true
                  python-version: ${{ matrix.python-version }}
                  cache-dependency-glob: '**/uv.lock'

            - name: Cache cargo and rust build
              uses: actions/cache@v5
              with:
                  path: |
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      rust/target/
                  key: cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock')
                      }}-${{ github.run_id }}
                  restore-keys: |
                      cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-${{ hashFiles('**/Cargo.lock') }}-
                      cargo-rust-target-${{ runner.os }}${{ runner.arch }}-python${{ steps.setup-uv.outputs.python-version }}-
                      cargo-rust-target-${{ runner.os }}${{ runner.arch }}-

            - name: Install artistools (no dev deps)
              run: |
                  rustup update stable
                  uv sync --no-dev --compile-bytecode

            - name: Check artistools command line tool
              run: |
                  artistools --help
                  artistools completions

            - name: Download/extract test data
              working-directory: tests/data/
              run: source ./setuptestdata.sh

            - name: Install dev deps
              run: uv sync --compile-bytecode

            - name: Test with pytest
              run: uv run --no-sync -- python -m pytest --cov=./ --cov-report=xml

            - name: Report coverage
              run: uv run -- python -m coverage report

            - uses: codecov/codecov-action@v7
              env:
                  OS: ubuntu-26.04${{ !endsWith(matrix.python-version, 't') && '-arm' || '' }}
                  PYTHON: ${{ matrix.python-version }}
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  files: ./coverage.xml
                  flags: unittests
                  env_vars: OS,PYTHON
                  name: codecov-umbrella
                  fail_ci_if_error: false
                  verbose: true
