name: Update packages

on:
  schedule:
    - cron: "16 22 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            cache: pip
            python-version-file: .python-version

      - name: Install requirements
        run: python -m pip install pur pre-commit

      - name: Run pre-commit autoupdate
        run: |
          pre-commit install
          pre-commit autoupdate

      - name: Run pur
        run: pur

      - name: Commit and push
        run: |
          git config --global user.email "luke.shingles@gmail.com"
          git config --global user.name "Autoupdate"
          git add ".pre-commit-config.yaml"
          git add "requirements.txt"
          git commit -m "Upgrade pre-commit dependencies"
          git push origin upgrade/pre-commit

      - name: Open pull request
        run: |
          gh pr create --fill