name: Update pre-commit

on:
  # every week on monday
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run autoupdate
        run: |
          pre-commit autoupdate

      - name: Commit and push
        run: |
          git add ".pre-commit-config.yaml"
          git commit -m "Upgrade pre-commit dependencies"
          git push origin upgrade/pre-commit

      - name: Open pull request
        run: |
          gh pr create --fill