name: Update packages

on:
    schedule:
        - cron: '00 10 * * *'
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    upgrade:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        env:
            GITHUB_TOKEN: ${{ github.token }}
        steps:
            - uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  cache: pip
                  python-version-file: .python-version

            - name: Install requirements
              run: |
                  python -m pip install -r requirements.txt
                  python -m pip install pur

            - name: run pur
              run: |
                  pur

            - uses: browniebroke/pre-commit-autoupdate-action@main

            - uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: update/packages
                  title: Update packages
                  commit-message: 'chore: update pre-commit hooks and packages'
                  body: Update versions of pre-commit hooks and python packages to latest versions.
